export const COMMON_COUNTRIES: string[] = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "New Zealand",
  "Ireland",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Portugal",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Japan",
  "South Korea",
  "Singapore",
  "India",
  "United Arab Emirates",
  "South Africa",
];
