export const INTERESTS_OPTIONS = [
  "Traveling",
  "Wine Tasting",
  "Fine Dining",
  "Casual Dining",
  "Sports",
  "Team Events",
  "Movies",
  "Theater",
  "Music Concerts",
  "Art Galleries",
  "Museums",
  "Hiking",
  "Beach",
  "Dancing",
  "Cooking",
  "Gaming",
  "Reading",
  "Photography",
  "Shopping",
  "Coffee",
  "Bars & Nightlife",
  "Quiet Places",
  "Adventure Sports",
  "Yoga & Wellness",
  "Festivals",
  "Comedy Shows",
  "Karaoke",
  "Board Games",
  "Picnics",
  "Road Trips",
  "Big Crowds",
  "Noisy Places",
  "Outdoor Activities",
  "Indoor Activities",
];